### ISSUE TITLE
Is there a disk image with config tools for the v2 Analog

### ISSUE THREAD

**Issue by roninfourseven** [V2RetroComputing/analog#11]
Apologies if I'm being dim here, but having just completed a build of a v2 Analog, on boot I get a nice clear screen, presumably from the RPi.

![PXL_20230413_103404153](https://user-images.githubusercontent.com/37797321/231765729-ba980f2b-bd49-453c-9a12-800f0af0d01f.jpg)

But my VGA screen is corrupt when attempting to run anything.

![PXL_20230413_103700002](https://user-images.githubusercontent.com/37797321/231766120-46de8908-a19b-4ec0-a249-278bff59286b.jpg)

It is clearly running though, but I'm assuming that there is a config utility that I need in order to specify something that will help with this? I've been looking for such a utility, but just can't seem to find a disk image, other than the empty prodos.dsk and the font.dsk image.

I am using the latest firmware, so 20230406 and I used the preloader first before I installed the VGA firmware.

I would add that I was unable to program the PAL ICs so used what appears to be an equivalent GAL I already had in my stock, but I don't know if that will affect the overall performance, if it simply needs configuring, or if there might be another issue.

I'd be grateful of any assistance anyone can offer.

**Comment by dkgrizzly** [comment]
First and foremost, check for shorts on the level shifters!
You can also try the latest firmware images from [the new modular builds](https://github.com/V2RetroComputing/analog-firmware). I've seen the "jail bar" pattern before on a board with a solder bridge between two pins of one of the level shifters.

There are new builds of both the firmware and utilities due out by this weekend with fixed config interfaces, font loading utility, and better compatibility with ROMX and ROMXe addons.

**Comment by roninfourseven** [comment]
Thanks so much for your advice, I went back this morning and rechecked all the level shifters and whilst I didn't find any shorts, I did find 2 pins on 2 different shifters that weren't correctly soldered. I've resoldered them and all is looking great :)

![PXL_20230414_080922048](https://user-images.githubusercontent.com/37797321/231985700-2ff32356-bdea-4ecc-a2ad-c27726816e7d.jpg)

![PXL_20230414_081032380](https://user-images.githubusercontent.com/37797321/231985834-eeb5386c-12f6-44b2-9390-c819160956db.jpg)

I'll keep an eye open for the new builds over the weekend, thanks so much for your assitsance and great job with the adapter :)

**Comment by dkgrizzly** [comment]
Glad you were able to get your board working!
The utilities and firmware mentioned before have now been released.
