### ISSUE TITLE
5.25" Floppy disks boot and hang at V2 Analog message

### ISSUE THREAD

**Issue by roninfourseven** [V2RetroComputing/analog#13]
I downloaded the V2 Analog 5.25" disk images as I am unable to use the 3.25" images at present.
My Apple IIe has dual V2 Analog cards, one for VGA, the other configured as an Applicard.
I am able to boot into CP/M successfully using the Applicard disk images and VGA works fine.

However, when I boot from disk525a.dsk, the machine starts but hangs on a screen with the message V2 Analog.

Nothing further happens after that and I am unable to use any of the config tools.

**Comment by dkgrizzly** [comment]
Please try loading the config.enh system file after booting with another prodos disk. I may need to make some adjustments to the boot menu / machine detection wrappers.

**Comment by roninfourseven** [comment]
Sure, I'll give it a try and let you know the outcome. 

Regards

Jon

**Comment by roninfourseven** [comment]
Hi there, and sorry if this is a dumb question, I'm getting back into the Apple IIe after 40 years and I'm very rusty, but I've hit a wall trying to run config.enh.

I can boot from a blank ProDOS disk and swap to disk525a.dsk, and when I run a CAT on the drive, I can see config.enh in the file listing for D1. 

So far all good, but when I try to run config.enh I'm not having any luck.

I am assuming the correct command in ProDOS is: -config.enh?
If I run that I get the message "No buffers available".
If I execute -menu.base however, I do get a menu and can load the config utility, and I'm also able to read and save the configuration.
If I execute -menu.system it hangs with V2 Analog at the top left of the screen.

**Comment by dkgrizzly** [comment]
Is that IIe an "enhanced" with the 65C02 or the unenhanced IIe without the 65C02?  I have not tested the card on the unenhanced IIe, so there may be some things that need more work (for one thing, Autodetect code will probably think its a II+ and not a IIe)

**Comment by dkgrizzly** [comment]
And also for the unenhanced you will need to run the .base file instead.  I'll double check that the launcher utility gets updated to run the .base file for unenhanced systems instead of the .enh version.

**Comment by dkgrizzly** [comment]
Please try the disk images from the latest [release](https://github.com/V2RetroComputing/analog/releases/tag/20230421).

**Comment by roninfourseven** [comment]
Ahh, I see. It's a standard Apple IIe, not the enhanced , so just a plain 6502. I'll try the lates images and get back to you.
I'm happy to test on my unenhanced IIe if you need me to, thanks.

**Comment by roninfourseven** [comment]
Thanks, the disks all boot and take me to the menu system and config tools now. One quick question, disks C & D both seem to have font manager on them, is this correct? This is what I have:
1. disk525a.dsk - config tools
2. disk525b.dsk - ADTPro at a ProDOS prompt
3. disk525c.dsk - Font manager
4. disk525d.dsk - Font manager

And I couldn't see a specific difference with font manager on either disk c or d.

**Comment by dkgrizzly** [comment]
So the fonts matching slots 00-0F are on disk C and slots 10-27 are on disk D with an extra copy of the 00 base font.
The fonts don't all currently fit on the same disk, even with compression.  Uncompressed fonts take up 4 blocks, and compressed fonts take up 1-3 blocks, but require a matching "base font".  The compression is very simple, the differences between the base font and the font being compressed are taken, then the result is run length encoded to shrink the file down by 1-3 blocks in size.  The fonts that didn't compress well I left uncompressed since they didn't shrink enough to save a disk block.

**Comment by roninfourseven** [comment]
Ahh, cool, all make sense now :)
