### ISSUE TITLE
Applicard mode 80 column colours

### ISSUE THREAD

**Issue by roninfourseven** [V2RetroComputing/analog#14]
Hi

Having just configured the Applicard, I have some odd 80 column behaviour when booting from a standard Applicard disk and one  with an 80 column configuration.

My machine is an Apple IIe PAL model.

If I boot with the standard disk and no card in the AUX slot, CP/M boots into 40 column mode. The display is reflected by the VGA adpter.

If I boot with a RAM/80 column card in the Aux slot of my Apple IIe, the standard disk goes into 80 column mode, but there is no display on the VGA port other than the splash screen for the v2Analog. This is the 80 column display shown via composite:

![PXL_20230420_123053483](https://user-images.githubusercontent.com/37797321/233367621-29e2f7c7-a8d8-470d-8862-2a967da15783.jpg)

When booting with the AUX slot empty using the Applicard disk 2 that boots immediately into 80 column mode, I get an 80 column mode with bad fringing on composite:

![PXL_20230420_110450986](https://user-images.githubusercontent.com/37797321/233368768-7280fc8a-90c8-413f-961a-f6b299a07be2.jpg)

And on VGA it is reflected, but has extreme fringing and is very hard to read:

![PXL_20230420_110456398](https://user-images.githubusercontent.com/37797321/233368950-4531efe0-22bb-412b-bb26-e35edb07d17c.jpg)

Finally, booting from the 80 column 2nd Applicard disk with the AUX slot populated, I get the same fringing with the screen  mirrored onto VGA.

Any help or advice gratefully received and I am more than happy to help with any testing.

**Comment by dkgrizzly** [comment]
That looks like it is using the software terminal driver which draws on one of the HGR pages and not using the native text hardware.  Try using one of the other Applicard / Starcard boot disks and see if one of them has the updated Apple IIe 80 column drivers.

This is the disk I was using to test with [Google Drive Link](https://drive.google.com/file/d/1QWmTIr_IuHy3osJ5PWWkEbIYc6zPgTVL/view?usp=share_link)

**Comment by dkgrizzly** [comment]
* the later two pictures are using the software 70 column driver.  There is a register on the card to set monochrome mode 
From the monitor rom you can enter
`C0n1:80`
with n being the slot the card is in + 8
That will disable all color decoding and draw the raw black & white 560x192 raster.
Then boot into CP/M with 6 <Ctrl-P> from the monitor prompt.

**Comment by roninfourseven** [comment]
Thanks so much for your responses, I will give your suggestions a try and will let you know how it goes.

Regards

Jon

**Comment by roninfourseven** [comment]
Using the 'basic80.po' disk image form your link, I get the same results as with 'PCPI AppliCard - StarCard Disk 1.po'.
With an 80 cloumn/RAM card in the AUX slot, it boots to 80 columns but it is not mirrored on the VGA display.
With nothing in the AUX slot, it boots to CP/M in 40 column mode and the display is mirrored on the VGA display.

With regards to the 2nd group of pictures, I tried the C0n1:80 option in the monitor, with n as both 4 and also 12 (The card is in slot 4), but I still get the heavily fringed display on both the composite and VGA screens. I also tried a number of other variations but I still get the heavily fringed output. I tried a lot of variations too.

The commands I tried, based on C0n1:80 with n=slot number + 8 were:

1. C04:80
2. C012:80
3. C041:80
4. C0121:80

All were followed by 6 CTRL+K ENTER to boot from the drive in slot 6, which worked fine to boot into CP/M.
I'm not sure I ran the commands correctly as I am very rusty with my Apple IIe. Not sure if it being PAL makes a difference BTW.

**Comment by dkgrizzly** [comment]
The card doing VGA output is in slot 4? in that case C0C1:80   n being a hex number of the slot + 8 (so C081 for slot 0, C0F1 for slot 7).  I have not tested the config utility fully to verify that setting it to default to monochrome mode works yet.

**Comment by roninfourseven** [comment]
Duh, thats me being dumb and using decimal, sorry.

**Comment by roninfourseven** [comment]
Hmm, so for some reason, 6 CTRL+K ENTER is no longer booting from slot 6 in the monitor and I don't know why.

I'll keep trying and let you know how I get on.

**Comment by roninfourseven** [comment]
Hi.

I've managed to do some more testing at the weekend, but things are still the same:

1. Booting into the Applicard disk provided by you with RAM installed into the AUX slot of my IIe gives 80 column text in CP/M but it isn't mirrored to VGA. This is the case if I use the original Applicard disk too.
2. Booting into the Applicard disk provided by you with the AUX slot empty, the Applicard disk you provided boots into 40 column CP/M and the screen is mirrored to VGA.
3. Regardless of how I set the register, or the slot I use,  whilst the display is mirrored to the VGA card, I still see the colour fringing with disk 2 of the original Applicard set. This is the same regardless of the AUX slot being populated or not.

Regards

Jon

**Comment by roninfourseven** [comment]
Ok, so here's the way it works for me.

1. Boot into ProDOS in 40 column mode, VGA mirrors the 40 columns, then typing PR#3 gives me 80 column mode on both composite and VGA.
2. I boot to the Apple ][ prompt and press CTRL+Reset to skip booting and go into 40 column mode at the basic prompt. Typing PR#3 takes me to 80 column mode but it isn't mirrored by VGA.
3. Removing the FDD controller, if I boot straight into basic and type PR#3 I get 80 columns in basic, but it isn't mirrored on VGA.
Just to add, booting straight to basic, even with the AUX slot empty, I don't get the 40 column display mirrored on VGA, that only happens when I boot from a disk.

I'll test the fringing issue once you release the new firmware.

Thanks

Jon

**Comment by roninfourseven** [comment]
A quick additional comment. 

If I boot into ProDOS in 40 column mode, VGA mirrors the 40 columns, then typing PR#3 from BASIC gives me 80 column mode on both composite and VGA.

If I then switch the disk to the BASIC80 image you linked to and type PR#6 I can boot to CP/M from BASIC and the screen remains mirrored on the VGA adapter.

No other scenarios allow me to use the CP/M mode in 80 column mode. Using the 2nd Applicard disk still give me the fringed display, but it does at least show on both displays from the get go.

**Comment by dkgrizzly** [comment]
Please try the new firmware and utilities build https://github.com/V2RetroComputing/analog/releases/tag/20230502
and let me know if you still are experiencing issues.

**Comment by roninfourseven** [comment]
Hi there.

I tried the new firmware and I am now getting an instant mirror and can boot into CP/M mode in 80 columns right away.

That is with both the BASIC80 disk you provided and Applicard disk 1, so I'm very happy with that.

The Applicard disk 2 still shows the fringing, but I'm not really too worried since the others worked no problem, and I believe you explained that as being down to a software 70 column driver.

So far so good :)

However, I am seeing another issue. I say issue, but I don't know if it is down to configuration of the card or the firmware.

When I boot something like Elite, that has a large white splash screen, I see this:

![PXL_20230505_081623836](https://user-images.githubusercontent.com/37797321/236416146-0ebee7cf-182c-4273-b5a8-a96293d80240.jpg)

The left image is the v2 Analog, the right is composite. Prior to the firmware update, the v2 Analog was sharp and clear, but after upgrading, the image is muddy, and looking closely it seems to have stripes:

![PXL_20230505_085759960](https://user-images.githubusercontent.com/37797321/236417810-84127d4c-2bcf-4f1d-826f-bcdd1422a787.jpg)

Obviously the fact that the v2 Analog now immediately mirrors CP/M as soon as I boot and recognises 80 columns is fantastic, however the graphics change is not ideal. If there are changes you can suggest in the config utility, I'd be happy to try them, otherwise I'll have to switch back to the earlier firmware for the image quality and manage the CP/M side with my workaround (Boot to dos, PR#3 for 80 column, change to a CP/M disk and boot using PR#6)

I hope that's helpful feedback, and I'm more than happy to try any firmware you want me to.

Regards

Jon

**Comment by roninfourseven** [comment]
Hi there. I was doing some testing and found a better way of showing the display issues I noted in my last post.

This is composite:

![Composite](https://user-images.githubusercontent.com/37797321/236440824-86703a8c-a2e6-48aa-9bd2-7f8182bdf882.jpg)

And this is VGA with the latest firmware from the same machine:

![v2_Analog_VGA_Pre_Release_FW](https://user-images.githubusercontent.com/37797321/236441107-a5a5715a-f23d-44fa-83a6-b4322f68d52d.jpg)

As you can see, the display is very grainy. It changed to this when I used the updated firmware.

**Comment by roninfourseven** [comment]
Just by way of comparison, this is the same screen with the earlier firmware:

![PXL_20230505_111618044](https://user-images.githubusercontent.com/37797321/236444154-3de7741a-4b18-466c-b7d9-7432a9a23635.jpg)

And a shot of the Elite splash screen with the old firmware:

![PXL_20230505_110623689](https://user-images.githubusercontent.com/37797321/236443404-d5795bf3-c0f2-498a-8180-82d0423869da.jpg)

I totally get it's pre release and just hope I can help in some way.

**Comment by roninfourseven** [comment]
I just applied the 20230504 Release, replacing 20230502 to my v2 and everything looks good so far. Thanks very much, I now get things back as they were before, but the VGA display now also mirrors right from the start as soon as I power on and also works immediately with the Z80 mode disks without having to boot with something else, switch to 80 column then PR#6 the Applicard software. Great work sir, thank you.
