### ISSUE TITLE
v2 Analog and Mockingboard clash

### ISSUE THREAD

**Issue by roninfourseven** [V2RetroComputing/analog#16]
I have hit an interesting issue with my boards, of which I have 2.

Board 1 is the first I built, and works fine as both the VGA adapter and as the Applicard.

Board 2 is the second I built, used all components from the same batches, bar the RPi and the diode and works fine as both the VGA adapter and as the Applicard.

There are some subtle difference, in that board 2 has an RPi that is about a year newer, and the diode is not quite the same. Board 1 has an SS34 diode as recommended by somebody here (Not you I don't think) and board 2 has an SS14 diode as per the latest BOM here. 

The problem I have is that when using board 1, my Mockingboard is detected fine, but aside from the bootup beep, there is no sound. It makes no difference if board 1 is configured for VGA or Z80, I get no sound from the Mockingboard.

If I use board 2, whether it be in VGA or Z80 mode, the Mockingboard works just fine. 

Both were configured with the same preloader and firmware. I have tried using the 8ns firmware (VGA and Z80) but it made no difference.

I can't imagine the diode would have any affect, but I will change it anyway. 

Both use a GAL16V8D in place of the PAL, but both boards seem to work normally, so it seems odd that one works and the othe prevents the Mockingboard from running.

I have been through board 1 and cant find any shorts, and have checked all the soldering is good across each component.

If there are specific hardware things that you think might clash with the Mockingboard, I'd be grateful of any ideas you have where I could look.

I have tried varying combinations of expansion slot BTW, but board 1 always prevents the Mockingboard from working.

Thanks and Regards

Jon

**Comment by dkgrizzly** [comment]
I don't think the diode should cause much difference, the SS34 is just overkill since the board should never end up drawing 1 amp let alone 3 amps.  I would start by checking all the solder connections, and check for any warm chips.  With no other cards in the computer, you should see the card's config memory at $CnF0-$CnFF with n being the slot number the card is installed in (1 thru 7). If a copy shows up in another slot, the GAL might not be working correctly.

**Comment by roninfourseven** [comment]
Great, thanks for the pointers, I'll do some digging and see what I can find.

Thinking back, I'm sure it did originally work, and all I've done since then was touch up the RPi solder joints, and whilst I have already checked for shorts and bad joints and not found any, I will go at it again.

Regards

Jon

**Comment by roninfourseven** [comment]
Hey there. I went through some 'one step at a time' troubleshooting today and it turns out the 2nd level shifter from the front  of the card was faulty.
Oddly, it wasn't bad enough to stop VGA or Applicard working, just to block the Mockingboard.
I replaced it earlier and everything is working as expected :)

Thanks for your great product and support :)
