### ISSUE TITLE
Non functional Applicard mode on firmware 145; also gets stuck in that mode

### ISSUE THREAD

**Issue by misterblack1** [V2RetroComputing/analog#2]
Setting the card to Applicard mode disables VGA. (By design.) But then the Applicard boot disk does not boot CPM, it just hangs at a black screen when looking at Composite video. (CPM disk works on a real Applicard on the same machine.)

Trying to change back to VGA mode fails because the config utility reports time-out. 

I had to use the ML monitor to manually switch back to VGA mode by writting:
C=VGA and then DC at C4F0h. (My card is in slot 4.) Card comes back to life and work again.

Config utility can communicate with the card again.

**Comment by dkgrizzly** [comment]
Build 0159 has working PCPI mode, but escaping back is still finicky.

The FORMAT command is more appropriate, as sending the DC command with all zeros will upload $0000-$03FF as the config file of the card and could cause further problems.

Replace n with the slot number the card is installed in:

]CALL -151
*CnF0:46 4F 52 4D 41 54 00 00

**Comment by misterblack1** [comment]
This is working great now. I had to format the card to get out of PCPI mode, but I was able to boot into CPM without issue. Excellent!
