### ISSUE TITLE
nLRESET not connected

### ISSUE THREAD

**Issue by rallepalaveev** [V2RetroComputing/analog#21]
In the schematic nLRESET (U4, pin7) does not seem to be connected. On the PCB the tracing starts from the chip but ends under the Pico unconnected. Is it intended for pin 30 of the Pico (Run)? Perhaps it can be connected via a jumper so it can be connected or disconnected depending on the application?

**Comment by dkgrizzly** [comment]
The reset pin is disconnected on purpose as it would cause the RP2040 to reset everytime the Apple II is reset, and this would cause the RP2040 to come out of reset too late to capture the first few cycles of 6502 activity, and be unable to autodetect the host type.

Instead, the sequence of reading FFFE and FFFF is used to detect reading of the reset vector when a reset occurs after the system is booted.

**Comment by rallepalaveev** [comment]
Thank you.
