### ISSUE TITLE
Need help with my card build, almost there but not quite.

### ISSUE THREAD

**Issue by Verault** [V2RetroComputing/analog#25]
I have built two cards and they both seem to have the same issue. I am not sure what is wrong. I have gone over them a few times. Reprogrammed the PAL and added the preload before adding the vga firmware. Both show similar screens via vga output. See screen shots. What am I missing?
![IMG_20231108_184836](https://github.com/V2RetroComputing/analog/assets/64697404/f7e60f28-5688-4f39-b49d-fddb9240c193)
![IMG_20231108_184907](https://github.com/V2RetroComputing/analog/assets/64697404/a19025d0-a445-4506-b216-c191b0d71e91)

**Comment by mamejay** [comment]
Try and mash the reset key sequence a few times.  Normally on the 3rd try it will come up

**Comment by Verault** [comment]
I tried a couple times. I guess I should try more. You think thats all it is? Will this happen every time or just for the first initial boot?

Im trying in an un-enhanced IIe 1982 board model if that has anything at all to do with it,

**Comment by mamejay** [comment]
Everytime from my experience. Using the older firmware I did not have any issues

**Comment by Verault** [comment]
Really? Thats not good at all. if thats the case I would be happy to try the older firmware. 

Which version of the older firmware have you had the best luck with?

**Comment by mamejay** [comment]
Try 20230406 version.  Had graphics issues in hires mode but seemed to boot first try.
Also if that don't work remove the PAL and jumper the board to just rule that out

**Comment by mamejay** [comment]
[20230406.zip](https://github.com/V2RetroComputing/analog/files/13303483/20230406.zip)
Here you go

**Comment by Verault** [comment]
Thank you mamejay! I will try this tomorrow. Can I just drop the new firmware on the cards or should I do the preload first?

**Comment by mamejay** [comment]
I would do the pre-load first.  Always do just in case

**Comment by Verault** [comment]
Understood. Thank you again. Will post results tomorrow.

**Comment by rallepalaveev** [comment]
The VGA functionality should work without the PAL, you can try without it while shorting the pins marked by "NOPAL". Another thing to try is use the 4ns firmware. Make sure to use wifi firmware if your Pico has wifi, if not, the LC firmware.

**Comment by Verault** [comment]
IF the old firmware mamejay doesnt have an affect I will try the nopal option next to see if the issues are the PAL's. Also I have been using the 4ns LC-VGA firmware (no wireless).

**Comment by Verault** [comment]
Ok I have an update. I tried what Mamejay said about mashing the restart buttons and it didnt do anything for one card it seems but the other gave me colored blocks.
![IMG_20231109_112409](https://github.com/V2RetroComputing/analog/assets/64697404/854f7e6c-cff9-48b4-916d-1ffc5bd99c71)

Also this same card gave a different color line pattern if I did onboard diags check.
![IMG_20231109_112439](https://github.com/V2RetroComputing/analog/assets/64697404/794026c3-d116-4d9b-bf25-ae46fab2c254)

I ran the preload on both cards and then the old firmware and I am now getting this same screen on both cards now.
![IMG_20231109_113013](https://github.com/V2RetroComputing/analog/assets/64697404/2b0bbec8-6b47-41f6-b0ea-bcba98e215ac)
![IMG_20231109_112913](https://github.com/V2RetroComputing/analog/assets/64697404/66a506dc-99f1-403d-8f02-87e5febe3066)


So what does this mean? My PAL's are not working? I can try the no pal next if you guys think that is the correct move.
Also here is a copy of the JED file I got as an output of WINCUPL, can you verify its correct?
[PicoPal.zip](https://github.com/V2RetroComputing/analog/files/13310596/PicoPal.zip)


Also just want to note, I was using the 4ns LC VGA firmware initially when testing these cards.

**Comment by dkgrizzly** [comment]
The PAL and nopal jumper aren't needed for VGA only functionality. they enable the card to detect the slot-specific I/O accesses, but it will still see all writes regardless of the PAL or jumper being used. Usually when a card doesn't see bus activity it indicates the right most level shifter is installed wrong or bad. if it sees activity but it's corrupt or blank, that indicates one of the other shifters is the problem. Check that the dot on the chips indicating pin one is aligned with the longer white stripe on the silkscreen. The next versions of the card have clearer silkscreen markings for pin 1. Also check that there are no shorts between adjacent pins, or legs lifted preventing connection.

**Comment by Verault** [comment]
Thanks I did check and found no shorts. But I can check again.

**Comment by Verault** [comment]
I removed the PAL and connected the NoPAL signal. One of the cards is now outputting the Apple II screen out via VGA. The other still says No bus activity so I need to investigate the level shifter as dkgrizzly mentioned.  

Either way I think this means neither of my PALS are working.

**Comment by Verault** [comment]
I have just swapped out the lcx16245 ics. The one that works has toshiba TCLCX16245 but I bought a roll of motorolla lcx16245 ics. I can not get the card to see bus activity and I am sure the ics are connected properly. Have you heard of this? I suppose I should buy more Toshiba TCLCX16245 IC's.

**Comment by Verault** [comment]
Anyone have any ideas on this?

**Comment by dkgrizzly** [comment]
74LCX16245 is not the part used on my version of the board, and is a single-supply chip. If the board was designed for the dual-rail 74LVC16T245, it may be part of the problem.  The 74LCX16245 chips should only be supplied with 3.3V on all of the VCC inputs.  It would help to know which PCB you have.  Even without the PAL chip or jumper, the PHI signal and all address and data lines are passed to the PICO and you should get video. The cardselect lines are only needed for Z80 mode, and interacting with the config utility.

**Comment by Verault** [comment]
My apologies. I am using Hans Huebners' fork. https://github.com/hanshuebner/AppleII-VGA

**Comment by dkgrizzly** [comment]
I would also suggest trying Mark's 1.0.0 firmware release, see if it makes any difference. He has backported some of the changes I and others have made, and some folks have had better results running his firmware.  https://github.com/markadev/AppleII-VGA/releases/tag/v1.0.0   I don't know what all features he has implemented beyond the IIe modes, so the config util and multiple fonts are almost certainly off the table.

**Comment by Verault** [comment]
Thank you. I will give this a try.

**Comment by Verault** [comment]
I realize I never updated this. All set closing the issue.
