### ISSUE TITLE
Need help with Z80 functionality

### ISSUE THREAD

**Issue by rallepalaveev** [V2RetroComputing/analog#26]
Hi, I have built the card with VGA functionality with the PLD and it works well. However, when I flash the Z80 firmware, CPM cannot boot as it says it can't find a Z80 card. Is there anything in particular that I need to look at?

**Comment by dkgrizzly** [comment]
You have to use the Applicard software and have the card in slot 4. It does not work with CPM for Microsoft's Softcard or other CPM distros for the Apple II. Only Applicard or the rebranded versions of it.

**Comment by rallepalaveev** [comment]
Thank you David - this solved it, Applicard SW worked at once.
