### ISSUE TITLE
Auto detection still doesn't quite work right

### ISSUE THREAD

**Issue by misterblack1** [V2RetroComputing/analog#4]
Set to auto on a IIe, it seems to end up in II+ mode. 

Setting manually in the config utility is a viable workaround.

**Comment by dkgrizzly** [comment]
The firmware boot time was long enough that autodetection was failing quite a bit.  I've reworked the firmware so the code that interacts with the Apple II bus starts up faster, and then the VGA or Z80 code is copied to ram and started.

**Comment by dkgrizzly** [comment]
Autodetection appears to be working correctly now on all the systems I have to test with under Release 20230417.
