### ISSUE TITLE
VGA output stays in 80 column mode after a reset

### ISSUE THREAD

**Issue by misterblack1** [V2RetroComputing/analog#5]
If you are using 80 column software, resetting the Apple II leaves the VGA output in 80 column mode. Could you watch the execution of the reset vector and drop the system back to 40 column?

**Comment by dkgrizzly** [comment]
Doing exactly that in the new firmware builds here: https://github.com/V2RetroComputing/analog-firmware
Successive reads of the reset vector and the jump to $FA62 will cause the softswitch state in the firmware to reset.
This should work on all Apple II models and most clones.  Replacement ROMs or cards that intercept the reset vector may prevent this detection from working, but requiring all three memory reads back to back is the best way to prevent false triggers.

**Comment by dkgrizzly** [comment]
Resolved in the new 20230417 Release Builds
