### ISSUE TITLE
Project web site down?

### ISSUE THREAD

**Issue by pkooiman** [V2RetroComputing/analog#6]
I am having trouble accessing the project web site, it seems v2retrocomputing.com is not being resolved right now.

dig v2retrocomputing.com
; <<>> DiG 9.16.32 <<>> v2retrocomputing.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: SERVFAIL, id: 36810
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0

**Comment by DominikPalo** [comment]
I'm having the same issue - my DNS is not able to resolve the v2retrocomputing.com domain: `DNS_PROBE_FINISHED_NXDOMAIN`

**Comment by Sommerbo** [comment]
It is a server-side/configuration issue. I checked with an online up/down checker

**Comment by Verault** [comment]
Since the website is down can someone please point me to a BOM for this card since I am printing out the board and making it myself?

**Comment by DominikPalo** [comment]
@Verault I've just generated an interactive BOM file from the project, just extract it and open open in your webbrowser: [ibom.zip](https://github.com/V2RetroComputing/analog/files/11069843/ibom.zip)

**Comment by Verault** [comment]
> @Verault I've just generated an interactive BOM file from the project, just extract it and open open in your webbrowser: [ibom.zip](https://github.com/V2RetroComputing/analog/files/11069843/ibom.zip)

DominikPalo you are a rockstar! Thank you so much. I really love these interactive BOMs by the way, the are fantastic!

**Comment by Verault** [comment]
> @Verault I've just generated an interactive BOM file from the project, just extract it and open open in your webbrowser: [ibom.zip](https://github.com/V2RetroComputing/analog/files/11069843/ibom.zip)

Thank you so much Dominik, I just noticed a few components dont have values: C1 through C9 for instance.

**Comment by DominikPalo** [comment]
@Verault yes, I noticed it too (it's not the issue with the BOM generator - the C1-C9 values are not present even in the project). But all those caps are just power rail bypass caps for level shifters and according to the SN74LVC8T245 datasheet, the recommended value is  0.1 µF (100 nF)

**Comment by hanshuebner** [comment]
If you have trouble sourcing the level shifter or want to save on PCB costs, you may be interested in my fork of this project which makes a couple of changes:

- Cheaper level shifters
- 2 layer PCB instead of four
- 0603 passives instead of 0402
- Snap-off VGA connector with IDC headers to connect them
- Pico reset button
- Pico footprint with holes so that socket can be used if desired
- DB15HD footprint with fixed distance between pin rows
- Component cables on silk screen for easier builds

I'm about to send the first production order to JLCPCB, so the design is yet untested.  Maybe it is worth the wait if you want to build the board yourself.

**Comment by Verault** [comment]
@hanshuebner How exciting! Yes I can wait! This sounds much easier. Good luck.

**Comment by Verault** [comment]
@hanshuebner Will you post Gerbers when they are past prototype debugging?

**Comment by mamejay** [comment]
> If you have trouble sourcing the level shifter or want to save on PCB costs, you may be interested in [my fork](https://github.com/hanshuebner/AppleII-VGA) of this project which makes a couple of changes:
> 
> * Cheaper level shifters
> * 2 layer PCB instead of four
> * 0603 passives instead of 0402
> * Snap-off VGA connector with IDC headers to connect them
> * Pico reset button
> * Pico footprint with holes so that socket can be used if desired
> * DB15HD footprint with fixed distance between pin rows
> * Component values on silk screen for easier builds
> 
> I'm about to send the first production order to JLCPCB, so the design is yet untested. Maybe it is worth the wait if you want to build the board yourself.

I have just had a look at your PCB and its amazing work.  Love the DB15 snap off option included.  Once you get your test PCB's back please let us know if they are working as I have a few people here in Australia interested.
Also while I have you can you use any variant of the PALCE16V8H PAL?  Mention /5 in the original design but I can get /4 ones cheaper.
Thanks

**Comment by hanshuebner** [comment]
> Also while I have you can you use any variant of the PALCE16V8H PAL? Mention /5 in the original design but I can get /4 ones cheaper.

/4 should be fine.  From the [datasheet](file:///Users/hans/Downloads/PALCE16V8PALCE16V8ZDataSheet%20(3).PDF):

<img width="450" alt="image" src="https://user-images.githubusercontent.com/108751/228126900-334fb17f-e43c-4f79-9684-0bc0a3945dee.png">

**Comment by mamejay** [comment]
Awesome!! I did see that datasheet and thought it should be ok.  I have order some now.

**Comment by Verault** [comment]
> > @Verault I've just generated an interactive BOM file from the project, just extract it and open open in your webbrowser: [ibom.zip](https://github.com/V2RetroComputing/analog/files/11069843/ibom.zip)
> 
> I am in the process of ordering parts, but the BoM doesn't mention the type of diode, other than it's Schottky. Are you able to say what the part number is please?

I was thinking : https://rarecomponents.com/store/ss34

**Comment by JCWNTRS** [comment]
> BAT54, 1N5822 or any other diode with a low voltage drop will do. The diode is there to prevent current from flowing from the RPi's USB port into the Apple, so its speed is not critical. Even an 1N4148 will likely do as the RPi Pico regulates the input down to 3.3V anyway.

Thank you!

**Comment by dkgrizzly** [comment]
Fixed the issue with the DNS.  As for the diode, https://www.lcsc.com/product-detail/Schottky-Barrier-Diodes-SBD_Shikues-SS14F_C110213.html is the part I'm currently using.
