### ISSUE TITLE
Can you use a PALCE16V8H-5JC/4 instead of PALCE16V8H-5JC/5

### ISSUE THREAD

**Issue by mamejay** [V2RetroComputing/analog#8]
Hello there,
I am looking to make a few of these for my local computer group and found that PALCE16V8H-5JC/4 PAL's are much cheaper to get my hands on,  Can these be used?
From the datasheet it just looks like PALCE16V8H-5JC/5 is the newer revision PAL.

Thanks

**Comment by dkgrizzly** [comment]
The part I'm using is an [ATF16V8C-5JX](https://www.digikey.com/en/products/detail/microchip-technology/ATF16V8C-5JX/1027054) which is still currently produced and in stock at most distributors.
